# 通过---切换不同文档（文档块）
server:
  port: 8081
spring:
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod

# person:
#   name: hjh
#   age: 20
#   boss: false
#   maps:
#     k1: v1
#     k2: v2
#   lists:
#     - list1
#     - list2
#   dog:
#     name: 小卡
#     age: 2

# # 冒号后必有空格